### ISSUE TITLE
Farmer's Dashboard's crops price not working properly

### ISSUE THREAD

**Issue by SujanNeupane42** [prajwalad101/aims#10]
![no_price_data](https://user-images.githubusercontent.com/85225585/166183959-1f0991b1-cca8-40b6-b27a-1319e336c5b2.PNG)

@Prajwalad101 Please see to this issue as quickly as possible. I just checked the system by logging in as farmer. And, I found out the bar chart to visualize the prices of farmer's chosen crops is not working at all. This issue needs to be fixed ASAP!

**Comment by prajwalad101** [comment]
Faulty data was passed into the price chart which is causing the issue. I have fixed the data and now the chart works properly

![price chart](https://user-images.githubusercontent.com/84787320/166184728-61187876-3ffa-4437-a484-9e40fb0a59f9.PNG)
