### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by prajwalad101** [prajwalad101/aims#3]
Application shows compile time error and shows it cannot find the utils folder

![compile error](https://user-images.githubusercontent.com/84787320/162714611-6b015307-e5e2-46c7-a556-9e5c36e2b0a6.PNG)
.

**Comment by SujanNeupane42** [comment]
Please double-check the path of the utils folder, and also check the input statement.

**Comment by prajwalad101** [comment]
Thanks. Fixing the import statement resolved the error
