### ISSUE TITLE
User dashboard shows no data

### ISSUE THREAD

**Issue by prajwalad101** [prajwalad101/aims#4]
Chartjs displays empty data on user dashboard

![no data](https://user-images.githubusercontent.com/84787320/162715742-e3ed7a9a-5a25-48fa-81c0-72cdca0b89f6.PNG)

**Comment by SujanNeupane42** [comment]
Please double-check if the data you have used on dashboard to create charts is empty or not!

**Comment by prajwalad101** [comment]
The issue existed because of wrong logic on the formatting function. Checking for null values, fixed the issue. Thanks
