### ISSUE TITLE
Unexpected token / in JSON

### ISSUE THREAD

**Issue by prajwalad101** [prajwalad101/aims#5]
When compiling the application, the terminal shows a unexpected token error

![json error](https://user-images.githubusercontent.com/84787320/162716985-093b8594-8f9b-43f6-8214-65b2c8e245e7.PNG)
.

**Comment by SujanNeupane42** [comment]
please check the package.json file for any faults. That might do the job

**Comment by prajwalad101** [comment]
Thanks. package.json definitely seemed to be the problem. running npm install fixed the issue
