### ISSUE TITLE
Sign in page

### ISSUE THREAD

**Issue by SujanNeupane42** [prajwalad101/aims#6]
![sign in page](https://user-images.githubusercontent.com/85225585/162725500-e67dafa0-d5b4-474b-81b9-080fdc90bc11.PNG)
The sign-in page does not look much appealing. Perhaps the product name and company logo would be much better on the login page. Please see to this change immediately.

**Comment by prajwalad101** [comment]
This is the new update sign in page. I have made some design changes by adding images and styling of buttons.

![updatedSignIN](https://user-images.githubusercontent.com/84787320/162726397-8f4dc538-9f4b-472d-a602-2a80dae3359e.PNG)

**Comment by SujanNeupane42** [comment]
Well done
