### ISSUE TITLE
Menus overlaying with each other

### ISSUE THREAD

**Issue by SujanNeupane42** [prajwalad101/aims#7]
Please modify the code such that the menu dropdown does not overlap with the product list.
![productsList](https://user-images.githubusercontent.com/85225585/162726083-ffe9f1b5-45a7-4a33-8faf-c1c7fa0fa5d1.PNG)

**Comment by prajwalad101** [comment]
Here is the update layout of the product list. I have made changes according to your request.

![productsList updated](https://user-images.githubusercontent.com/84787320/162726546-35fa9874-0bd3-43eb-a43d-4b14cd522d56.PNG)
