### ISSUE TITLE
PDF download button not working

### ISSUE THREAD

**Issue by SujanNeupane42** [prajwalad101/aims#8]
![issue1](https://user-images.githubusercontent.com/85225585/166183251-2fb16816-02f9-4860-acd8-1b99577a5b06.png)
@Prajwalad101  Please see to this issue. The feature to download user data in CSV format is not working.

**Comment by prajwalad101** [comment]
Wrong ref was being passed into the download component. I have fixed this issue now.

![pdf button](https://user-images.githubusercontent.com/84787320/166184803-7fd3f266-ee8c-4176-9675-28e16bae351e.PNG)
