### ISSUE TITLE
Admin's Dashboard's Users linegraph not working

### ISSUE THREAD

**Issue by SujanNeupane42** [prajwalad101/aims#9]
![issue2](https://user-images.githubusercontent.com/85225585/166183798-ed5a8976-ba37-4d0a-96e8-c5439e91eb3c.png)

@Prajwalad101  Please solve this issue asap! The line graph to visualize the users in the admin's dashboard is not working properly. This needs to be fixed ASAP!

**Comment by prajwalad101** [comment]
This issue is being caused due to incorrectly formatted data. I have fixed the data and now it works.

![admin graph](https://user-images.githubusercontent.com/84787320/166184897-3354895f-2ca3-46ac-a29a-5f1e22c831c9.PNG)
